title: Project-a
description: "Project-a — решения на стыке Machine Learning и информационной безопасности: защищённые ИИ-алгоритмы нового поколения."
author: Project-a
lang: ru

remote_theme: pages-themes/hacker@v0.2.0

show_downloads: false
